# Generated by Django 5.2.3 on 2025-07-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_blocked",
        ),
    ]
