# Generated by Django 5.2.3 on 2025-07-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_customuser_is_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
