# Generated by Django 5.2.3 on 2025-07-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmail',
            name='name',
            field=models.CharField(default=1, max_length=250, unique=True, verbose_name='Название рассылки'),
            preserve_default=False,
        ),
    ]
