# Generated by Django 5.2.3 on 2025-07-16 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_bulkmail_owner_receiver_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkmail',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Рассылки', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bulkmail',
            name='status',
            field=models.CharField(choices=[('Завершена', 'Завершена'), ('Создана', 'Создана'), ('Запущена', 'Запущена')], default='Создана', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bulkmailattempt',
            name='status',
            field=models.CharField(choices=[('Успешно', 'Успешно'), ('Не успешно', 'Не успешно')], default='successful', max_length=10, verbose_name='Статус'),
        ),
    ]
