# Generated by Django 5.2.3 on 2025-07-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_alter_bulkmail_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkmail',
            options={'permissions': (('can_disable_mail', 'Can disable mail'),), 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
